export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const UPDATE_CUSTOMERS = 'UPDATE_CUSTOMERS';
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
